image: bradqwood/rust-build-docker:1.3.1

stages:
  - lint
  - test
  - publish
  - build

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

lint:
  stage: lint
  cache:
    paths:
      - target/
      - .cargo/
  script:
    - rustup --version
    - just lint
  only:
    - branches

test:
  stage: test
  cache:
    paths:
      - target/
      - .cargo/
  script:
    - just tarp
  artifacts:
    expose_as: coverage report
    expire_in: 1 week
    paths:
      - tarp/tarpaulin-report.html
  only:
    - branches

publish to crates.io:
  stage: publish
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  script:
    # check that the git tag semver string is the same as the string in Cargo.toml
    - test $(grep version Cargo.toml| head -1 | cut -f3 -d\ ) = \"$CI_COMMIT_TAG\"
    - cargo publish --token $CRATES_DOT_IO_KEY --allow-dirty

build musl package:
  stage: build
  image: registry.gitlab.com/rust_musl_docker/image:stable-latest
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  script:
    - apt-get update -qq && apt-get -y -qq install jq
    - export BUILD_DIR=git_lab_cli-${CI_COMMIT_TAG}-x86_64-unknown-linux-musl
    - export TARBALL=${BUILD_DIR}.tar.gz
    - cargo build --release --target=x86_64-unknown-linux-musl
    - mkdir -p ${BUILD_DIR}/man
    - find target/x86_64-unknown-linux-musl -type f -name 'git-lab' | xargs strip
    - find target/x86_64-unknown-linux-musl -type f -name 'git-lab' | xargs -i cp -p {} ${BUILD_DIR}
    - find target/x86_64-unknown-linux-musl -type f -name 'git-lab.1' | xargs -i cp -p {} ${BUILD_DIR}/man
    - cp LICENSE ${BUILD_DIR}
    - cp INSTALL ${BUILD_DIR}
    - cp README.md ${BUILD_DIR}
    - tar zcvf ${TARBALL} ${BUILD_DIR}
    - ./ci/release.sh
  artifacts:
    paths:
      - git_lab_cli*.tar.gz
