image: bradqwood/rust-build-docker:1.1.1

stages:
  # - lint
  - test
  # - publish

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

cache:
  paths:
    - target/
    - .cargo/

before_script:
  - rustup --version

test comms:
  stage: test
  script:
    - curl https://crates.io/

.lint:
  stage: lint
  script:
    - just lint
  only:
    - branches

.test:
  stage: test
  script:
    - just tarp
  artifacts:
    expose_as: coverage report
    paths: [tarp/tarpaulin-report.html]
  only:
    - branches

.publish:
  stage: publish
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  script:
    # check that the git tag semver string is the same as the string in Cargo.toml
    - test $(grep version Cargo.toml| head -1 | cut -f3 -d\ ) = \"$CI_COMMIT_TAG\"
    - cargo publish --token $CRATES_DOT_IO_KEY --allow-dirty -vv
