image: bradqwood/rust-build-docker:latest

before_script:
  - rustup --version
  - cargo install just

stages:
  - lint
  - unit test
  - integration test
  - publish

lint:
  stage: lint
  script:
    # -  cargo clippy
    - just lint

unit test:
  stage: unit test
  script:
    # - cargo clean
    - just clean
    # - cargo test -- --test-threads=1 --skip integration
    - just unit-test
    # - TARGET=$(find target/debug -maxdepth 1 -name "git_lab-*" -executable -type f -exec stat -c '%Y %n' {} \;  | sort -nr | head -1 |cut -f2 -d' ')
    # - echo unit test binary=$TARGET
    # - kcov --exclude-pattern=/.cargo,/usr/lib,/cargo --verify target/cov $TARGET --test-threads=1
    # - COVERAGE=$(grep -Po 'covered":.*?[^\\]"' target/cov/index.js | grep "[0-9]*\.[0-9]" -o)
    # - echo "Coverage:" $COVERAGE
    - just cov

integration test:
  stage: integration test
  script:
    # - cargo test -- --test-threads=1 --skip unit
    - just int-test

cargo publish:
  stage: publish
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
  script:
    # check that the git tag semver string is the same as the string in Cargo.toml
    - test $(grep version Cargo.toml| head -1 | cut -f3 -d\ ) = \"$CI_COMMIT_TAG\"
    - cargo publish --token $CRATES_DOT_IO_KEY --allow-dirty
