[package]
name = "git-lab"
version = "0.1.0"
authors = ["Bradley Wood <git@bradleywood.com>"]
edition = "2018"
description = "A git custom command for interacting with a GitLab server"
readme = "README.md"
repository = "https://gitlab.com/bradwood/git-lab-rust"
keywords = ["git", "Gitlab", "cli"]
categories = ["development-tools", "command-line-utilities"]
license = "MIT"

# [badges]
# gitlab = { repository = "bradwood/git-lab-rust" }

[dependencies]
clap = "2.33.0"
git2 = "0.13"
# dirs = "2"

# [dev-dependencies]
assert_cmd = "0.12"
assert_fs = "1.0"
predicates = "1.0"
# rstest = "0.6"
