[package]
name = "git-lab"
version = "0.1.0"
authors = ["Bradley Wood <git@bradleywood.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
# dirs = "2"

# [dev-dependencies]
# assert_cmd = "0.12"
# predicates = "1.0"
# rstest = "0.6"
